# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ghbill-dev-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        env:
          CI: true
          # Placeholders para variáveis que serão substituídas no ambiente de produção
          SESSION_SECRET: "placeholder-for-build"
          GITHUB_CLIENT_ID: "placeholder-for-build"
          GITHUB_CLIENT_SECRET: "placeholder-for-build"
          MONGODB_URI: "placeholder-for-build"

      - name: Create deployment package
        run: |
          zip -r release.zip . \
            --exclude=".git/*" \
            --exclude=".github/*" \
            --exclude="node_modules/*" \
            --exclude="tests/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7AC5128440A8461689803EDC84E8092A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BBBC8EB0EBC04155B02A4F2253AD91F5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D8EE015DF20B48E7BCD65A656745E921 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ghbill-dev-app'
          slot-name: 'Production'
          package: release.zip

      - name: Configure App Service
        run: |
          az webapp config appsettings set \
            --resource-group "ghbilling-rg" \
            --name "ghbill-dev-app" \
            --settings \
            ENABLE_ORYX_BUILD="true" \
            SCM_DO_BUILD_DURING_DEPLOYMENT="true" \
            WEBSITE_RUN_FROM_PACKAGE="1" \
            NODE_ENV="production" \
            WEBSITE_NODE_DEFAULT_VERSION="~18" \
            NPM_CONFIG_PRODUCTION="true"
